export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      {/* <meta content="width=device-width, initial-scale=1" name="viewport" /> */}
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
